name: vocab_mini_game
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.20.0
  audioplayers: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/PlayScreen/
    - assets/PlayScreen/CorrectAnswer/
    - assets/PlayScreen/FailAnswer/
    - "assets/PlayScreen/Star Bullet/"
    - assets/PlayScreen/ClickRipple/
    - assets/PlayScreen/SlowBorder/
    - assets/PlayScreen/SnailMoving/
    - assets/PlayScreen/SnowFlower/
    - assets/PlayScreen/Freeze/
    - assets/PlayScreen/MultipleScore/
    - assets/MainScreen/
    - assets/Others/
    - assets/Sounds/
